// <auto-generated />
using System;
using API_Hantonio_Jaramillo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Hantonio_Jaramillo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331073101_actualizacion")]
    partial class actualizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaNacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleCamisa", b =>
                {
                    b.Property<int>("IdDetalleCamisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleCamisa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleCamisa"));

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("ContrasteTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ContrasteTela");

                    b.Property<string>("EstiloBolsillo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsillo");

                    b.Property<string>("EstiloCuello")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloCuello");

                    b.Property<string>("EstiloPuno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloPuno");

                    b.Property<string>("EstiloTapeta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloTapeta");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Iniciales")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Iniciales");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<string>("OpcionCamisa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OpcionCamisa");

                    b.Property<int?>("OrdenIdOrden")
                        .HasColumnType("int");

                    b.Property<string>("PlieguesFrontales")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PlieguesFrontales");

                    b.Property<string>("PosicionContraste")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PosicionContraste");

                    b.Property<decimal>("PrecioCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioCamisa");

                    b.Property<string>("SolapaBolsillo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SolapaBolsillo");

                    b.HasKey("IdDetalleCamisa");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.HasIndex("OrdenIdOrden");

                    b.ToTable("DetalleCamisa");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleChaleco", b =>
                {
                    b.Property<int>("IdDetalleChaleco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleChaleco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleChaleco"));

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoBoton");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("EstiloBolsilloInf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloInf");

                    b.Property<string>("EstiloBolsilloPecho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloPecho");

                    b.Property<string>("EstiloBotones")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBotones");

                    b.Property<string>("EstiloCuello")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloCuello");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<int?>("OrdenIdOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioChaleco");

                    b.Property<string>("TerminacionInf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TerminacionInf");

                    b.HasKey("IdDetalleChaleco");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.HasIndex("OrdenIdOrden");

                    b.ToTable("DetalleChaleco");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetallePantalon", b =>
                {
                    b.Property<int>("IdDetallePantalon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetallePantalon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePantalon"));

                    b.Property<string>("AjusteCintura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AjusteCintura");

                    b.Property<string>("AlturaPretina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AlturaPretina");

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoBoton");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("EstiloBajos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBajos");

                    b.Property<string>("EstiloBolsilloReloj")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloReloj");

                    b.Property<string>("EstiloPliegues")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloPliegues");

                    b.Property<string>("EstiloPretina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloPretina");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<int?>("OrdenIdOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioPantalon");

                    b.HasKey("IdDetallePantalon");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.HasIndex("OrdenIdOrden");

                    b.ToTable("DetallePantalon");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleSaco", b =>
                {
                    b.Property<int>("IdDetalleSaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleSaco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleSaco"));

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoBoton");

                    b.Property<string>("CodigoForro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoForro");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("EstiloBolsilloInf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloInf");

                    b.Property<string>("EstiloBolsilloPecho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloPecho");

                    b.Property<string>("EstiloBolsilloTicket")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloTicket");

                    b.Property<string>("EstiloBotones")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBotones");

                    b.Property<string>("EstiloOjalDerecho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloOjalDerecho");

                    b.Property<string>("EstiloOjalIzquierdo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloOjalIzquierdo");

                    b.Property<string>("EstiloSolapa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloSolapa");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Monograma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Monograma");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<int?>("OrdenIdOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioSaco");

                    b.Property<string>("TamanoSolapa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TamanoSolapa");

                    b.HasKey("IdDetalleSaco");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.HasIndex("OrdenIdOrden");

                    b.ToTable("DetalleSaco");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.EstatusOrden", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEstatus");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdEstatus");

                    b.ToTable("EstatusOrden");

                    b.HasData(
                        new
                        {
                            IdEstatus = 1,
                            Descripcion = "Pendiente de medidas"
                        },
                        new
                        {
                            IdEstatus = 2,
                            Descripcion = "Toma de medidas"
                        },
                        new
                        {
                            IdEstatus = 3,
                            Descripcion = "En confección"
                        },
                        new
                        {
                            IdEstatus = 4,
                            Descripcion = "Entregado"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.MedidasOrden", b =>
                {
                    b.Property<int>("IdMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedida"));

                    b.Property<decimal?>("AlTerrillaPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AlTerrillaPantalon");

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Altura");

                    b.Property<decimal?>("AlturaCinturaDPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AlturaCinturaDPantalon");

                    b.Property<decimal?>("AlturaCinturaTPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AlturaCinturaTPantalon");

                    b.Property<decimal?>("AnchoTraseroCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AnchoTraseroCamisa");

                    b.Property<decimal?>("AnchoTraseroSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AnchoTraseroSaco");

                    b.Property<decimal?>("AntebrazoCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AntebrazoCamisa");

                    b.Property<decimal?>("AntebrazoSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AntebrazoSaco");

                    b.Property<decimal?>("BicepsCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BicepsCamisa");

                    b.Property<decimal?>("BicepsSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BicepsSaco");

                    b.Property<decimal?>("BrazaletePantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BrazaletePantalon");

                    b.Property<decimal?>("CaderaPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CaderaPantalon");

                    b.Property<decimal?>("CaderasCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CaderasCamisa");

                    b.Property<decimal?>("CaderasChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CaderasChaleco");

                    b.Property<decimal?>("CaderasSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CaderasSaco");

                    b.Property<decimal?>("CinturaPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CinturaPantalon");

                    b.Property<decimal?>("CollarCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CollarCamisa");

                    b.Property<decimal?>("CollarChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CollarChaleco");

                    b.Property<decimal?>("CollarSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CollarSaco");

                    b.Property<decimal?>("EntrepiernaPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EntrepiernaPantalon");

                    b.Property<decimal?>("EstomagoCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EstomagoCamisa");

                    b.Property<decimal?>("EstomagoChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EstomagoChaleco");

                    b.Property<decimal?>("EstomagoSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EstomagoSaco");

                    b.Property<decimal?>("HombroDelanteroCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HombroDelanteroCamisa");

                    b.Property<decimal?>("HombroDelanteroSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HombroDelanteroSaco");

                    b.Property<decimal?>("HombrosCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HombrosCamisa");

                    b.Property<decimal?>("HombrosSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HombrosSaco");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<decimal?>("LongitudCinturaDChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudCinturaDChaleco");

                    b.Property<decimal?>("LongitudCinturaDelantera")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudCinturaDelanteraSaco");

                    b.Property<decimal?>("LongitudCinturaDelanteraCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudCinturaDelanteraCamisa");

                    b.Property<decimal?>("LongitudDPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudDPantalon");

                    b.Property<decimal?>("LongitudEspaldaCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudEspaldaCamisa");

                    b.Property<decimal?>("LongitudEspaldaChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudEspaldaChaleco");

                    b.Property<decimal?>("LongitudEspaldaSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudEspaldaSaco");

                    b.Property<decimal?>("LongitudFrontalCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudFrontalCamisa");

                    b.Property<decimal?>("LongitudFrontalChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudFrontalChaleco");

                    b.Property<decimal?>("LongitudFrontalSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudFrontalSaco");

                    b.Property<decimal?>("LongitudIPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudIPantalon");

                    b.Property<decimal?>("LongitudMangaDCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudMangaDCamisa");

                    b.Property<decimal?>("LongitudMangaDSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudMangaDSaco");

                    b.Property<decimal?>("LongitudMangaICamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudMangaICamisa");

                    b.Property<decimal?>("LongitudMangaISaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongitudMangaISaco");

                    b.Property<decimal?>("MusloPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MusloPantalon");

                    b.Property<decimal?>("MuñecaCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MuñecaCamisa");

                    b.Property<decimal?>("MuñecaSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MuñecaSaco");

                    b.Property<decimal?>("NucaCinturaCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NucaCinturaCamisa");

                    b.Property<decimal?>("NucaCinturaChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NucaCinturaChaleco");

                    b.Property<decimal?>("NucaCinturaSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NucaCinturaSaco");

                    b.Property<int?>("OrdenIdOrden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PechoCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PechoCamisa");

                    b.Property<decimal?>("PechoChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PechoChaleco");

                    b.Property<decimal?>("PechoSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PechoSaco");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Peso");

                    b.Property<decimal?>("PosicionPrimerBCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PosicionPrimerBCamisa");

                    b.Property<decimal?>("PosicionPrimerBChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PosicionPrimerBChaleco");

                    b.Property<decimal?>("PosicionPrimerBSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PosicionPrimerBSaco");

                    b.Property<decimal?>("RodillaPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RodillaPantalon");

                    b.Property<string>("TallaZapato")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TallaZapato");

                    b.Property<decimal?>("TamañoInferiorChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TamañoInferiorChaleco");

                    b.Property<string>("TipoFit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoFit");

                    b.Property<decimal?>("VientreCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VientreCamisa");

                    b.Property<decimal?>("VientreChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VientreChaleco");

                    b.Property<decimal?>("VientreSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VientreSaco");

                    b.HasKey("IdMedida");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.HasIndex("OrdenIdOrden");

                    b.ToTable("MedidasOrden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CostoTotal");

                    b.Property<DateTime?>("FechaCitaMedidas")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCitaMedidas");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEventoEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEventoEntrega");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("IdEstatus");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal");

                    b.Property<int>("IdTipoTraje")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTraje");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("MontoAbonado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoAbonado");

                    b.HasKey("IdOrden");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoTraje");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direccion");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Sucursal");

                    b.HasData(
                        new
                        {
                            IdSucursal = 1,
                            Direccion = "C. del Fuego 226 A, Jardines del Moral, 37160 León de los Aldama, Gto.",
                            Estatus = true,
                            Nombre = "Sucursal Jardines del Moral",
                            Telefono = "477 799 3177"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.TipoTraje", b =>
                {
                    b.Property<int>("IdTipoTraje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTraje");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTraje"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdTipoTraje");

                    b.ToTable("TipoTraje");

                    b.HasData(
                        new
                        {
                            IdTipoTraje = 1,
                            Descripcion = "Dos piezas"
                        },
                        new
                        {
                            IdTipoTraje = 2,
                            Descripcion = "Tres piezas"
                        },
                        new
                        {
                            IdTipoTraje = 3,
                            Descripcion = "Saco"
                        },
                        new
                        {
                            IdTipoTraje = 4,
                            Descripcion = "Pantalón"
                        },
                        new
                        {
                            IdTipoTraje = 5,
                            Descripcion = "Chaleco"
                        },
                        new
                        {
                            IdTipoTraje = 6,
                            Descripcion = "Camisa"
                        },
                        new
                        {
                            IdTipoTraje = 7,
                            Descripcion = "Frac"
                        },
                        new
                        {
                            IdTipoTraje = 8,
                            Descripcion = "Chaque"
                        },
                        new
                        {
                            IdTipoTraje = 9,
                            Descripcion = "Smoking"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreUsuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoLogin");

                    b.Property<DateTime?>("UltimoLogout")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoLogout");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleCamisa", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", null)
                        .WithOne("DetalleCamisa")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleCamisa", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenIdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleChaleco", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", null)
                        .WithOne("DetalleChaleco")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleChaleco", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenIdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetallePantalon", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", null)
                        .WithOne("DetallePantalon")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetallePantalon", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenIdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleSaco", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", null)
                        .WithOne("DetalleSaco")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleSaco", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenIdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.MedidasOrden", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", null)
                        .WithOne("Medidas")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.MedidasOrden", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenIdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.EstatusOrden", "EstatusOrden")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Sucursal", "Sucursal")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.TipoTraje", "TipoTraje")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdTipoTraje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstatusOrden");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoTraje");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.EstatusOrden", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.Navigation("DetalleCamisa");

                    b.Navigation("DetalleChaleco");

                    b.Navigation("DetallePantalon");

                    b.Navigation("DetalleSaco");

                    b.Navigation("Medidas");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.TipoTraje", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
