// <auto-generated />
using System;
using API_Hantonio_Jaramillo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Hantonio_Jaramillo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.CatEstatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estatus");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstatus");

                    b.ToTable("CAT_ESTATUS");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.CatRecursosDiseno", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecurso"));

                    b.Property<string>("Atributo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("atributo");

                    b.Property<string>("CodigoValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_valor");

                    b.Property<string>("NombreMostrar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_mostrar");

                    b.Property<string>("Prenda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenda");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("url_imagen");

                    b.HasKey("IdRecurso");

                    b.ToTable("CAT_RECURSOS_DISENO");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.CatTipoTraje", b =>
                {
                    b.Property<int>("IdTipoTraje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_traje");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTraje"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoTraje");

                    b.ToTable("CAT_TIPO_TRAJE");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleCamisa", b =>
                {
                    b.Property<int>("IdDetalleCamisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_camisa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleCamisa"));

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_tela");

                    b.Property<string>("EstiloCuello")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estilo_cuello");

                    b.Property<string>("EstiloPuno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estilo_puno");

                    b.Property<int?>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    b.Property<string>("Iniciales")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("iniciales");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDetalleCamisa");

                    b.HasIndex("IdOrden")
                        .IsUnique()
                        .HasFilter("[id_orden] IS NOT NULL");

                    b.ToTable("DETALLE_CAMISA");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleSaco", b =>
                {
                    b.Property<int>("IdDetalleSaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_saco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleSaco"));

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_boton");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_tela");

                    b.Property<string>("EstiloBolsillo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estilo_bolsillo");

                    b.Property<string>("EstiloSolapa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estilo_solapa");

                    b.Property<int?>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    b.Property<string>("Monograma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("monograma");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDetalleSaco");

                    b.HasIndex("IdOrden")
                        .IsUnique()
                        .HasFilter("[id_orden] IS NOT NULL");

                    b.ToTable("DETALLE_SACO");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.LogAcceso", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_salida");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LOG_ACCESOS");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.MedidasOrden", b =>
                {
                    b.Property<int>("IdMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_medida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedida"));

                    b.Property<decimal?>("CCuello")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("c_cuello");

                    b.Property<decimal?>("CManga")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("c_manga");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    b.Property<string>("ObservacionesMedidas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones_medidas");

                    b.Property<decimal?>("PCadera")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("p_cadera");

                    b.Property<decimal?>("PCintura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("p_cintura");

                    b.Property<decimal?>("PLargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("p_largo");

                    b.Property<decimal?>("PTiro")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("p_tiro");

                    b.Property<decimal?>("SEstomago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("s_estomago");

                    b.Property<decimal?>("SHombros")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("s_hombros");

                    b.Property<decimal?>("SLargoFrente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("s_largo_frente");

                    b.Property<decimal?>("SPecho")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("s_pecho");

                    b.HasKey("IdMedida");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.ToTable("MEDIDAS_ORDEN");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<decimal?>("CostoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_total");

                    b.Property<DateTime?>("FechaCitaMedidas")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cita_medidas");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaEventoEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_evento_entrega");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("id_estatus");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<int?>("IdTipoTraje")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_traje");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_creador");

                    b.Property<bool>("IncluyeCamisa")
                        .HasColumnType("bit")
                        .HasColumnName("incluye_camisa");

                    b.Property<decimal?>("MontoAbonado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_abonado");

                    b.HasKey("IdOrden");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoTraje");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("ORDEN");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("ROL");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Encargado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("encargado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdSucursal");

                    b.ToTable("SUCURSAL");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_login");

                    b.Property<DateTime?>("UltimoLogout")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_logout");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleCamisa", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("DetalleCamisa")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleCamisa", "IdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleSaco", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("DetalleSaco")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleSaco", "IdOrden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.LogAcceso", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Usuario", "Usuario")
                        .WithMany("LogAccesos")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.MedidasOrden", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("MedidasOrden")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.MedidasOrden", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdCliente");

                    b.HasOne("API_Hantonio_Jaramillo.Models.CatEstatus", "Estatus")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdEstatus");

                    b.HasOne("API_Hantonio_Jaramillo.Models.Sucursal", "Sucursal")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdSucursal");

                    b.HasOne("API_Hantonio_Jaramillo.Models.CatTipoTraje", "TipoTraje")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdTipoTraje");

                    b.HasOne("API_Hantonio_Jaramillo.Models.Usuario", "UsuarioCreador")
                        .WithMany("OrdenesCreadas")
                        .HasForeignKey("IdUsuarioCreador");

                    b.Navigation("Cliente");

                    b.Navigation("Estatus");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoTraje");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol");

                    b.HasOne("API_Hantonio_Jaramillo.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSucursal");

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.CatEstatus", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.CatTipoTraje", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.Navigation("DetalleCamisa");

                    b.Navigation("DetalleSaco");

                    b.Navigation("MedidasOrden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.Navigation("LogAccesos");

                    b.Navigation("OrdenesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
