// <auto-generated />
using System;
using API_Hantonio_Jaramillo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Hantonio_Jaramillo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ciudad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaNacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleCamisa", b =>
                {
                    b.Property<int>("IdDetalleCamisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleCamisa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleCamisa"));

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("ContrasteTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ContrasteTela");

                    b.Property<string>("EstiloBolsillo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsillo");

                    b.Property<string>("EstiloCuello")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloCuello");

                    b.Property<string>("EstiloPuno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloPuno");

                    b.Property<string>("EstiloTapeta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloTapeta");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Iniciales")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Iniciales");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<string>("OpcionCamisa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OpcionCamisa");

                    b.Property<string>("PlieguesFrontales")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PlieguesFrontales");

                    b.Property<decimal>("PrecioCamisa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioCamisa");

                    b.HasKey("IdDetalleCamisa");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.ToTable("DetalleCamisa");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleChaleco", b =>
                {
                    b.Property<int>("IdDetalleChaleco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleChaleco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleChaleco"));

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoBoton");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("EstiloBolsilloInf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloInf");

                    b.Property<string>("EstiloBolsilloPecho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloPecho");

                    b.Property<string>("EstiloBotones")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBotones");

                    b.Property<string>("EstiloCuello")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloCuello");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("PrecioChaleco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioChaleco");

                    b.Property<string>("TerminacionInf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TerminacionInf");

                    b.HasKey("IdDetalleChaleco");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.ToTable("DetalleChaleco");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetallePantalon", b =>
                {
                    b.Property<int>("IdDetallePantalon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetallePantalon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePantalon"));

                    b.Property<string>("AjusteCintura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AjusteCintura");

                    b.Property<string>("AlturaPretina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AlturaPretina");

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoBoton");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("EstiloBajos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBajos");

                    b.Property<string>("EstiloBolsilloReloj")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloReloj");

                    b.Property<string>("EstiloPliegues")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloPliegues");

                    b.Property<string>("EstiloPretina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloPretina");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("PrecioPantalon")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioPantalon");

                    b.HasKey("IdDetallePantalon");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.ToTable("DetallePantalon");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleSaco", b =>
                {
                    b.Property<int>("IdDetalleSaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleSaco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleSaco"));

                    b.Property<string>("CodigoBoton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoBoton");

                    b.Property<string>("CodigoForro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoForro");

                    b.Property<string>("CodigoTela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoTela");

                    b.Property<string>("EstiloBolsilloInf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloInf");

                    b.Property<string>("EstiloBolsilloPecho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloPecho");

                    b.Property<string>("EstiloBolsilloTicket")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBolsilloTicket");

                    b.Property<string>("EstiloBotones")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloBotones");

                    b.Property<string>("EstiloOjalDerecho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloOjalDerecho");

                    b.Property<string>("EstiloOjalIzquierdo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloOjalIzquierdo");

                    b.Property<string>("EstiloSolapa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstiloSolapa");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<string>("Monograma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Monograma");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("PrecioSaco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioSaco");

                    b.Property<string>("TamanoSolapa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TamanoSolapa");

                    b.HasKey("IdDetalleSaco");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.ToTable("DetalleSaco");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.EstatusOrden", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEstatus");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdEstatus");

                    b.ToTable("EstatusOrden");

                    b.HasData(
                        new
                        {
                            IdEstatus = 1,
                            Descripcion = "Pendiente de medidas"
                        },
                        new
                        {
                            IdEstatus = 2,
                            Descripcion = "Toma de medidas"
                        },
                        new
                        {
                            IdEstatus = 3,
                            Descripcion = "En confección"
                        },
                        new
                        {
                            IdEstatus = 4,
                            Descripcion = "Entregado"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.MedidasOrden", b =>
                {
                    b.Property<int>("IdMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedida"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Altura");

                    b.Property<decimal?>("CamisaCuello")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CamisaCuello");

                    b.Property<decimal?>("CamisaManga")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CamisaManga");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    b.Property<decimal?>("PantCadera")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PantCadera");

                    b.Property<decimal?>("PantCintura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PantCintura");

                    b.Property<decimal?>("PantLargoDer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PantLargoDer");

                    b.Property<decimal?>("PantLargoIzq")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PantLargoIzq");

                    b.Property<decimal?>("PantMuslo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PantMuslo");

                    b.Property<decimal?>("PantTiro")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PantTiro");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Peso");

                    b.Property<decimal?>("SacoBiceps")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoBiceps");

                    b.Property<decimal?>("SacoCadera")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoCadera");

                    b.Property<decimal?>("SacoEstomago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoEstomago");

                    b.Property<decimal?>("SacoHombros")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoHombros");

                    b.Property<decimal?>("SacoLargoEspalda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoLargoEspalda");

                    b.Property<decimal?>("SacoLargoFrente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoLargoFrente");

                    b.Property<decimal?>("SacoMangaDer")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoMangaDer");

                    b.Property<decimal?>("SacoMangaIzq")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoMangaIzq");

                    b.Property<decimal?>("SacoPecho")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SacoPecho");

                    b.Property<string>("TallaZapato")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TallaZapato");

                    b.Property<string>("TipoFit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoFit");

                    b.HasKey("IdMedida");

                    b.HasIndex("IdOrden")
                        .IsUnique();

                    b.ToTable("MedidasOrden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdOrden");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CostoTotal");

                    b.Property<DateTime?>("FechaCitaMedidas")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCitaMedidas");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEventoEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEventoEntrega");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("IdEstatus");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal");

                    b.Property<int>("IdTipoTraje")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTraje");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("MontoAbonado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoAbonado");

                    b.HasKey("IdOrden");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoTraje");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direccion");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Sucursal");

                    b.HasData(
                        new
                        {
                            IdSucursal = 1,
                            Direccion = "C. del Fuego 226 A, Jardines del Moral, 37160 León de los Aldama, Gto.",
                            Estatus = true,
                            Nombre = "Sucursal Jardines del Moral",
                            Telefono = "477 799 3177"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.TipoTraje", b =>
                {
                    b.Property<int>("IdTipoTraje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoTraje");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTraje"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion");

                    b.HasKey("IdTipoTraje");

                    b.ToTable("TipoTraje");

                    b.HasData(
                        new
                        {
                            IdTipoTraje = 1,
                            Descripcion = "Dos piezas"
                        },
                        new
                        {
                            IdTipoTraje = 2,
                            Descripcion = "Tres piezas"
                        },
                        new
                        {
                            IdTipoTraje = 3,
                            Descripcion = "Saco"
                        },
                        new
                        {
                            IdTipoTraje = 4,
                            Descripcion = "Pantalón"
                        },
                        new
                        {
                            IdTipoTraje = 5,
                            Descripcion = "Chaleco"
                        },
                        new
                        {
                            IdTipoTraje = 6,
                            Descripcion = "Camisa"
                        },
                        new
                        {
                            IdTipoTraje = 7,
                            Descripcion = "Frac"
                        },
                        new
                        {
                            IdTipoTraje = 8,
                            Descripcion = "Chaque"
                        },
                        new
                        {
                            IdTipoTraje = 9,
                            Descripcion = "Smoking"
                        });
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("IdSucursal");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreUsuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoLogin");

                    b.Property<DateTime?>("UltimoLogout")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoLogout");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleCamisa", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("DetalleCamisa")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleCamisa", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleChaleco", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("DetalleChaleco")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleChaleco", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetallePantalon", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("DetallePantalon")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetallePantalon", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.DetalleSaco", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("DetalleSaco")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.DetalleSaco", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.MedidasOrden", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Orden", "Orden")
                        .WithOne("Medidas")
                        .HasForeignKey("API_Hantonio_Jaramillo.Models.MedidasOrden", "IdOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.EstatusOrden", "EstatusOrden")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Sucursal", "Sucursal")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.TipoTraje", "TipoTraje")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdTipoTraje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstatusOrden");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoTraje");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Usuario", b =>
                {
                    b.HasOne("API_Hantonio_Jaramillo.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Hantonio_Jaramillo.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.EstatusOrden", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Orden", b =>
                {
                    b.Navigation("DetalleCamisa");

                    b.Navigation("DetalleChaleco");

                    b.Navigation("DetallePantalon");

                    b.Navigation("DetalleSaco");

                    b.Navigation("Medidas");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.Sucursal", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_Hantonio_Jaramillo.Models.TipoTraje", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
